package com.example.if_dose.db;

import org.greenrobot.greendao.annotation.Entity;
import org.greenrobot.greendao.annotation.Generated;
import org.greenrobot.greendao.annotation.Id;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END

/**
 * Entity mapped to table "ALIMENT".
 */
@Entity
public class Aliment {

    @Id(autoincrement = true)
    private Long id;
    private String name;
    private Double glucide;
    private Double quantite;
    private Long category_id;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    @Generated(hash = 1015963046)
    public Aliment() {
    }

    public Aliment(Long id) {
        this.id = id;
    }

    @Generated(hash = 1366654650)
    public Aliment(Long id, String name, Double glucide, Double quantite, Long category_id) {
        this.id = id;
        this.name = name;
        this.glucide = glucide;
        this.quantite = quantite;
        this.category_id = category_id;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public Double getGlucide() {
        return glucide;
    }

    public void setGlucide(Double glucide) {
        this.glucide = glucide;
    }

    public Double getQuantite() {
        return quantite;
    }

    public void setQuantite(Double quantite) {
        this.quantite = quantite;
    }

    public Long getCategory_id() {
        return category_id;
    }

    public void setCategory_id(Long category_id) {
        this.category_id = category_id;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
