package com.example.if_dose.db;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import java.util.Map;

import com.example.if_dose.db.AlimentDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 *
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig alimentDaoConfig;

    private final AlimentDao alimentDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
        daoConfigMap) {
        super(db);

        alimentDaoConfig = daoConfigMap.get(AlimentDao.class).clone();
        alimentDaoConfig.initIdentityScope(type);

        alimentDao = new AlimentDao(alimentDaoConfig, this);

        registerDao(Aliment.class, alimentDao);
    }

    public void clear() {
        alimentDaoConfig.clearIdentityScope();
    }

    public AlimentDao getAlimentDao() {
        return alimentDao;
    }

}
